@echo off

echo ============================================
echo XP12 Deprecated Datarefs and Command Scanner
echo Version 0.1 - 2022.09.13
echo ============================================

echo --------------------------------------------
echo The following files use DEPRECATED datarefs
echo --------------------------------------------
findstr /S "sim/aircraft/bodies/acf_fuse_cd_array" .\*.obj
findstr /S "sim/cockpit/autopilot/airspeed_mode" .\*.obj
findstr /S "sim/cockpit/autopilot/heading_mode" .\*.obj
findstr /S "sim/cockpit/autopilot/altitude_mode" .\*.obj
findstr /S "sim/cockpit/autopilot/mode_hnav" .\*.obj
findstr /S "sim/cockpit/autopilot/mode_gls" .\*.obj
findstr /S "sim/cockpit/electrical/ah_bar" .\*.obj
findstr /S "sim/cockpit/pressure/bleed_air_on" .\*.obj
findstr /S "sim/cockpit/switches/anti_ice_on" .\*.obj
findstr /S "sim/cockpit/switches/EFIS_map_mode" .\*.obj
findstr /S "sim/flightmodel/engine/ENGN_thro_override" .\*.obj
findstr /S "sim/flightmodel/misc/jett_size" .\*.obj
findstr /S "sim/flightmodel/parts/strut_vrt_def_veh" .\*.obj
findstr /S "sim/flightmodel/position/magpsi" .\*.obj
findstr /S "sim/operation/failures/rel_antice" .\*.obj
findstr /S "sim/operation/failures/rel_ice_surf_boot" .\*.obj
findstr /S "sim/operation/override/override_camera" .\*.obj
findstr /S "sim/operation/prefs/reset_on_crash" .\*.obj
findstr /S "sim/weather/wind_turbulence_percent" .\*.obj
findstr /S "sim/weather/has_real_weather_bool" .\*.obj
findstr /S "sim/weather/use_real_weather_bool" .\*.obj
findstr /S "sim/weather/download_real_weather" .\*.obj
findstr /S "sim/weather/temperature_tropo_c" .\*.obj
findstr /S "sim/weather/tropo_alt_mtr" .\*.obj
findstr /S "sim/flightmodel2/gear/strut_vertical_deflection_mtr" .\*.obj

findstr /S "sim/aircraft/bodies/acf_fuse_cd_array" .\*.lua
findstr /S "sim/cockpit/autopilot/airspeed_mode" .\*.lua
findstr /S "sim/cockpit/autopilot/heading_mode" .\*.lua
findstr /S "sim/cockpit/autopilot/altitude_mode" .\*.lua
findstr /S "sim/cockpit/autopilot/mode_hnav" .\*.lua
findstr /S "sim/cockpit/autopilot/mode_gls" .\*.lua
findstr /S "sim/cockpit/electrical/ah_bar" .\*.lua
findstr /S "sim/cockpit/pressure/bleed_air_on" .\*.lua
findstr /S "sim/cockpit/switches/anti_ice_on" .\*.lua
findstr /S "sim/cockpit/switches/EFIS_map_mode" .\*.lua
findstr /S "sim/flightmodel/engine/ENGN_thro_override" .\*.lua
findstr /S "sim/flightmodel/misc/jett_size" .\*.lua
findstr /S "sim/flightmodel/parts/strut_vrt_def_veh" .\*.lua
findstr /S "sim/flightmodel/position/magpsi" .\*.lua
findstr /S "sim/operation/failures/rel_antice" .\*.lua
findstr /S "sim/operation/failures/rel_ice_surf_boot" .\*.lua
findstr /S "sim/operation/override/override_camera" .\*.lua
findstr /S "sim/operation/prefs/reset_on_crash" .\*.lua
findstr /S "sim/weather/wind_turbulence_percent" .\*.lua
findstr /S "sim/weather/has_real_weather_bool" .\*.lua
findstr /S "sim/weather/use_real_weather_bool" .\*.lua
findstr /S "sim/weather/download_real_weather" .\*.lua
findstr /S "sim/weather/temperature_tropo_c" .\*.lua
findstr /S "sim/weather/tropo_alt_mtr" .\*.lua
findstr /S "sim/flightmodel2/gear/strut_vertical_deflection_mtr" .\*.lua

findstr /S "sim/aircraft/bodies/acf_fuse_cd_array" .\*.snd
findstr /S "sim/cockpit/autopilot/airspeed_mode" .\*.snd
findstr /S "sim/cockpit/autopilot/heading_mode" .\*.snd
findstr /S "sim/cockpit/autopilot/altitude_mode" .\*.snd
findstr /S "sim/cockpit/autopilot/mode_hnav" .\*.snd
findstr /S "sim/cockpit/autopilot/mode_gls" .\*.snd
findstr /S "sim/cockpit/electrical/ah_bar" .\*.snd
findstr /S "sim/cockpit/pressure/bleed_air_on" .\*.snd
findstr /S "sim/cockpit/switches/anti_ice_on" .\*.snd
findstr /S "sim/cockpit/switches/EFIS_map_mode" .\*.snd
findstr /S "sim/flightmodel/engine/ENGN_thro_override" .\*.snd
findstr /S "sim/flightmodel/misc/jett_size" .\*.snd
findstr /S "sim/flightmodel/parts/strut_vrt_def_veh" .\*.snd
findstr /S "sim/flightmodel/position/magpsi" .\*.snd
findstr /S "sim/operation/failures/rel_antice" .\*.snd
findstr /S "sim/operation/failures/rel_ice_surf_boot" .\*.snd
findstr /S "sim/operation/override/override_camera" .\*.snd
findstr /S "sim/operation/prefs/reset_on_crash" .\*.snd
findstr /S "sim/weather/wind_turbulence_percent" .\*.snd
findstr /S "sim/weather/has_real_weather_bool" .\*.snd
findstr /S "sim/weather/use_real_weather_bool" .\*.snd
findstr /S "sim/weather/download_real_weather" .\*.snd
findstr /S "sim/weather/temperature_tropo_c" .\*.snd
findstr /S "sim/weather/tropo_alt_mtr" .\*.snd
findstr /S "sim/flightmodel2/gear/strut_vertical_deflection_mtr" .\*.snd

echo --------------------------------------------
echo The following files use REMOVED commands
echo --------------------------------------------
findstr /S "sim/FMS/clear" .\*.obj
findstr /S "sim/FMS/direct" .\*.obj
findstr /S "sim/FMS/fix_next" .\*.obj
findstr /S "sim/FMS/fix_prev" .\*.obj
findstr /S "sim/FMS/init" .\*.obj
findstr /S "sim/FMS/key_load" .\*.obj
findstr /S "sim/FMS/key_save" .\*.obj
findstr /S "sim/FMS/sign" .\*.obj
findstr /S "sim/FMS/type_apt" .\*.obj
findstr /S "sim/FMS/type_fix" .\*.obj
findstr /S "sim/FMS/type_latlon" .\*.obj
findstr /S "sim/FMS/type_ndb" .\*.obj
findstr /S "sim/FMS/type_vor" .\*.obj
findstr /S "sim/GPS/coarse_select_down" .\*.obj
findstr /S "sim/GPS/coarse_select_up" .\*.obj
findstr /S "sim/GPS/fine_select_down" .\*.obj
findstr /S "sim/GPS/fine_select_up" .\*.obj
findstr /S "sim/engines/TOGA_power" .\*.obj
findstr /S "sim/flight_controls/glider_tow_straight" .\*.obj
findstr /S "sim/general/toggle_artificial_stab_win" .\*.obj
findstr /S "sim/general/toggle_autopilot_constants_win" .\*.obj
findstr /S "sim/general/toggle_control_deflections_win" .\*.obj
findstr /S "sim/general/toggle_fadec_win" .\*.obj
findstr /S "sim/general/toggle_weapon_guidance_win" .\*.obj
findstr /S "sim/operation/Air_Drop_from_B_52" .\*.obj
findstr /S "sim/operation/Air_Refuel_Basket" .\*.obj
findstr /S "sim/operation/Air_Refuel_Boom" .\*.obj
findstr /S "sim/operation/Grass_Field_Takeoff" .\*.obj
findstr /S "sim/operation/Gravel_Field_Takeoff" .\*.obj
findstr /S "sim/operation/Helipad_Takeoff" .\*.obj
findstr /S "sim/operation/Space_Shuttle_Final_Approach" .\*.obj
findstr /S "sim/operation/Space_Shuttle_Final_Re_entry" .\*.obj
findstr /S "sim/operation/Space_Shuttle_Full_Approach" .\*.obj
findstr /S "sim/operation/Space_Shuttle_Full_Re_entry" .\*.obj
findstr /S "sim/operation/Water_Way_Takeoff" .\*.obj
findstr /S "sim/operation/carry_other_aircraft" .\*.obj
findstr /S "sim/operation/load_real_weather" .\*.obj
findstr /S "sim/operation/stab_deriv_heading" .\*.obj
findstr /S "sim/operation/stab_deriv_pitch" .\*.obj
findstr /S "sim/operation/start_carried" .\*.obj
findstr /S "sim/operation/toggle_sky_colors_win" .\*.obj

findstr /S "sim/FMS/clear" .\*.lua
findstr /S "sim/FMS/direct" .\*.lua
findstr /S "sim/FMS/fix_next" .\*.lua
findstr /S "sim/FMS/fix_prev" .\*.lua
findstr /S "sim/FMS/init" .\*.lua
findstr /S "sim/FMS/key_load" .\*.lua
findstr /S "sim/FMS/key_save" .\*.lua
findstr /S "sim/FMS/sign" .\*.lua
findstr /S "sim/FMS/type_apt" .\*.lua
findstr /S "sim/FMS/type_fix" .\*.lua
findstr /S "sim/FMS/type_latlon" .\*.lua
findstr /S "sim/FMS/type_ndb" .\*.lua
findstr /S "sim/FMS/type_vor" .\*.lua
findstr /S "sim/GPS/coarse_select_down" .\*.lua
findstr /S "sim/GPS/coarse_select_up" .\*.lua
findstr /S "sim/GPS/fine_select_down" .\*.lua
findstr /S "sim/GPS/fine_select_up" .\*.lua
findstr /S "sim/engines/TOGA_power" .\*.lua
findstr /S "sim/flight_controls/glider_tow_straight" .\*.lua
findstr /S "sim/general/toggle_artificial_stab_win" .\*.lua
findstr /S "sim/general/toggle_autopilot_constants_win" .\*.lua
findstr /S "sim/general/toggle_control_deflections_win" .\*.lua
findstr /S "sim/general/toggle_fadec_win" .\*.lua
findstr /S "sim/general/toggle_weapon_guidance_win" .\*.lua
findstr /S "sim/operation/Air_Drop_from_B_52" .\*.lua
findstr /S "sim/operation/Air_Refuel_Basket" .\*.lua
findstr /S "sim/operation/Air_Refuel_Boom" .\*.lua
findstr /S "sim/operation/Grass_Field_Takeoff" .\*.lua
findstr /S "sim/operation/Gravel_Field_Takeoff" .\*.lua
findstr /S "sim/operation/Helipad_Takeoff" .\*.lua
findstr /S "sim/operation/Space_Shuttle_Final_Approach" .\*.lua
findstr /S "sim/operation/Space_Shuttle_Final_Re_entry" .\*.lua
findstr /S "sim/operation/Space_Shuttle_Full_Approach" .\*.lua
findstr /S "sim/operation/Space_Shuttle_Full_Re_entry" .\*.lua
findstr /S "sim/operation/Water_Way_Takeoff" .\*.lua
findstr /S "sim/operation/carry_other_aircraft" .\*.lua
findstr /S "sim/operation/load_real_weather" .\*.lua
findstr /S "sim/operation/stab_deriv_heading" .\*.lua
findstr /S "sim/operation/stab_deriv_pitch" .\*.lua
findstr /S "sim/operation/start_carried" .\*.lua
findstr /S "sim/operation/toggle_sky_colors_win" .\*.lua

findstr /S "sim/FMS/clear" .\*.snd
findstr /S "sim/FMS/direct" .\*.snd
findstr /S "sim/FMS/fix_next" .\*.snd
findstr /S "sim/FMS/fix_prev" .\*.snd
findstr /S "sim/FMS/init" .\*.snd
findstr /S "sim/FMS/key_load" .\*.snd
findstr /S "sim/FMS/key_save" .\*.snd
findstr /S "sim/FMS/sign" .\*.snd
findstr /S "sim/FMS/type_apt" .\*.snd
findstr /S "sim/FMS/type_fix" .\*.snd
findstr /S "sim/FMS/type_latlon" .\*.snd
findstr /S "sim/FMS/type_ndb" .\*.snd
findstr /S "sim/FMS/type_vor" .\*.snd
findstr /S "sim/GPS/coarse_select_down" .\*.snd
findstr /S "sim/GPS/coarse_select_up" .\*.snd
findstr /S "sim/GPS/fine_select_down" .\*.snd
findstr /S "sim/GPS/fine_select_up" .\*.snd
findstr /S "sim/engines/TOGA_power" .\*.snd
findstr /S "sim/flight_controls/glider_tow_straight" .\*.snd
findstr /S "sim/general/toggle_artificial_stab_win" .\*.snd
findstr /S "sim/general/toggle_autopilot_constants_win" .\*.snd
findstr /S "sim/general/toggle_control_deflections_win" .\*.snd
findstr /S "sim/general/toggle_fadec_win" .\*.snd
findstr /S "sim/general/toggle_weapon_guidance_win" .\*.snd
findstr /S "sim/operation/Air_Drop_from_B_52" .\*.snd
findstr /S "sim/operation/Air_Refuel_Basket" .\*.snd
findstr /S "sim/operation/Air_Refuel_Boom" .\*.snd
findstr /S "sim/operation/Grass_Field_Takeoff" .\*.snd
findstr /S "sim/operation/Gravel_Field_Takeoff" .\*.snd
findstr /S "sim/operation/Helipad_Takeoff" .\*.snd
findstr /S "sim/operation/Space_Shuttle_Final_Approach" .\*.snd
findstr /S "sim/operation/Space_Shuttle_Final_Re_entry" .\*.snd
findstr /S "sim/operation/Space_Shuttle_Full_Approach" .\*.snd
findstr /S "sim/operation/Space_Shuttle_Full_Re_entry" .\*.snd
findstr /S "sim/operation/Water_Way_Takeoff" .\*.snd
findstr /S "sim/operation/carry_other_aircraft" .\*.snd
findstr /S "sim/operation/load_real_weather" .\*.snd
findstr /S "sim/operation/stab_deriv_heading" .\*.snd
findstr /S "sim/operation/stab_deriv_pitch" .\*.snd
findstr /S "sim/operation/start_carried" .\*.snd
findstr /S "sim/operation/toggle_sky_colors_win" .\*.snd

echo --------------------------------------------
echo The following files use REMOVED datarefs
echo --------------------------------------------
findstr /S "sim/flightmodel/misc/C_m" .\*.obj
findstr /S "sim/flightmodel/misc/C_n" .\*.obj
findstr /S "sim/flightmodel/misc/ett_size" .\*.obj
findstr /S "sim/flightmodel/misc/stab_hdng_test" .\*.obj
findstr /S "sim/flightmodel/misc/stab_ptch_test" .\*.obj
findstr /S "sim/flightmodel/parts/elem_inc" .\*.obj
findstr /S "sim/flightmodel2/gear/gear_heading_deg" .\*.obj
findstr /S "sim/flightmodel2/gear/gear_pitch_deg" .\*.obj
findstr /S "sim/flightmodel2/gear/gear_roll_deg" .\*.obj
findstr /S "sim/graphics/animation/lights/vasi_papi_tint" .\*.obj
findstr /S "sim/graphics/colors/plane_path1_3d_rgb" .\*.obj
findstr /S "sim/graphics/colors/plane_path2_3d_rgb" .\*.obj
findstr /S "sim/graphics/misc/kill_runway_snow" .\*.obj
findstr /S "sim/graphics/settings/draw_forestfires" .\*.obj
findstr /S "sim/graphics/view/dome_number_of_passes" .\*.obj
findstr /S "sim/joystick/joystick_heading_augment" .\*.obj
findstr /S "sim/joystick/joystick_pitch_augment" .\*.obj
findstr /S "sim/joystick/joystick_roll_augment" .\*.obj
findstr /S "sim/multiplayer/controls/rotor_trim" .\*.obj
findstr /S "sim/operation/failures/rel_g_bat1" .\*.obj
findstr /S "sim/operation/failures/rel_g_bat2" .\*.obj
findstr /S "sim/operation/failures/rel_g_bus1" .\*.obj
findstr /S "sim/operation/failures/rel_g_bus2" .\*.obj
findstr /S "sim/operation/failures/rel_g_comrad1" .\*.obj
findstr /S "sim/operation/failures/rel_g_comrad2" .\*.obj
findstr /S "sim/operation/failures/rel_g_gen1" .\*.obj
findstr /S "sim/operation/failures/rel_g_gen2" .\*.obj
findstr /S "sim/operation/failures/rel_g_navrad1" .\*.obj
findstr /S "sim/operation/failures/rel_g_navrad2" .\*.obj
findstr /S "sim/operation/failures/rel_g_xpndr" .\*.obj
findstr /S "sim/operation/failures/rel_gen_avio" .\*.obj
findstr /S "sim/operation/failures/rel_pyl1a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl1b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl2a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl2b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl3a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl3b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl4a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl4b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl5a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl5b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl6a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl6b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl7a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl7b" .\*.obj
findstr /S "sim/operation/failures/rel_pyl8a" .\*.obj
findstr /S "sim/operation/failures/rel_pyl8b" .\*.obj
findstr /S "sim/weather/sigma" .\*.obj
findstr /S "sim/weather/thermal_percent" .\*.obj
findstr /S "sim/world/boat/carrier_catshot_end_x_mtrtrack" .\*.obj
findstr /S "sim/world/boat/carrier_catshot_end_z_mtrtrack" .\*.obj
findstr /S "sim/world/boat/carrier_catshot_headingheading" .\*.obj
findstr /S "sim/world/boat/carrier_catshot_start_x_mtr" .\*.obj
findstr /S "sim/world/boat/carrier_catshot_start_z_mtr" .\*.obj
findstr /S "sim/world/boat/carrier_catshot_status" .\*.obj

pause
